version: '3.8'

services:
  db:
    container_name: db
    image: postgres:16
    env_file:
      - .env
    ports:
      - '5432:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - dev

  application:
    container_name: application
    build:
      context: ./src
      dockerfile: Dockerfile
    volumes:
      - ./src:/app
    entrypoint: ["/entrypoint.sh"]
    ports:
      - '5173:5173'
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - dev

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    env_file:
      - .env
    ports:
      - "5050:80"
    networks:
      - dev

networks:
  dev:
    driver: bridge
